import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LayoutProps } from '@/types/page';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learn App Router",
  description: "Generated by Mykola Fant",
};

interface LayoutSlots {
  article: ReactNode;
}

const IS_LEARNING_ENABLED = true;

export default function RootLayout({
  article,
  children,
}: LayoutProps & LayoutSlots) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {IS_LEARNING_ENABLED && article}
      </body>
    </html>
  );
}
